### ISSUE TITLE
Missing some Material 3 color tones

### ISSUE THREAD

**Issue by pauldemarco** [JavierM42/tailwind-material-colors#3]
As per the spec:
https://m3.material.io/styles/color/the-color-system/tokens#7fd4440e-986d-443f-8b3a-4933bff16646

For instance, `surface-container-lowest`.

It looks like the current implementation is more Material 2: https://m2.material.io/design/color/the-color-system.html

**Comment by JavierM42** [comment]
It's definitely missing those. I figure I missed them because they don't appear on the [Material Theme Builder](https://m3.material.io/theme-builder#/custom).

I'll try to find the time to add them in so it matches the spec. Thank you so much for the heads up!

**Comment by pauldemarco** [comment]
This library rocks! I love using official material token names while coloring my components.
Adding those missing tokens will really let me lock down per the spec. As of right now, I'm getting close to the missing tokens by using Tailwind's opacity modifier, i.e. `bg-surface/50`.

**Comment by JavierM42** [comment]
It seems the Material Team has updated quite a few things on their end, so it's not just about adding the missing tokens and values.

There's different schemes for different kinds of content now (such as Vibrant, Monochrome, Expressive and Content, among a few others), they've also added a contrast parameter to tweak the schemes even further. Supporting these would be pretty cool, but it certainly involves some breaking changes because the default scheme now outputs slightly different colors.

I'm not sure that they're not going to shake things up again, so I'm a bit hesitant to jump into it. I'll add it to my backlog with a low priority anyway. Or if you want to jump into it, it's super appreciated of course. I can provide a few ideas/pointers on where to start.

**Comment by beautyfree** [comment]
There was a need for other colors, for example primary-fixed-dim. 

Found it in the material library https://github.com/material-foundation/material-color-utilities/blob/6018b1765f3e67c9414712c303444f8f25f27fcd/typescript/dynamiccolor/dynamic_color_test.ts#L84

**Comment by marios1861** [comment]
Is there any update on this? Surface containers are included in the [Material Theme Builder](https://www.figma.com/community/plugin/1034969338659738588/material-theme-builder) now.

**Comment by JavierM42** [comment]
Thanks for the heads up. I don't have much free time to dedicate to this library at the moment, but I'll get to it eventually :)

**Comment by marios1861** [comment]
I'll look into it and give you a pull request if I get it done. It's a very nice library for making pretty things fast in tailwind using the MD3 guidelines.

**Comment by JavierM42** [comment]
Update: I've got a rough working version, I'll tidy it up and publish when I get the chance.

**Comment by JavierM42** [comment]
V3 released with the colors in the theme builder (surface bright/dim/lowest/low/high/highest), as well as different named scheme configurations (vibrant, tonal spot, expressive, etc) and contrast setting support.

**Comment by pauldemarco** [comment]
Can’t wait to try this out!

**Comment by chloerei** [comment]
I'm developing a material design style website and this library helps me a lot. 👍

**Comment by JavierM42** [comment]
This has been solved for a while now, closing 🎉

**Comment by pauldemarco** [comment]
Looks great @JavierM42 . Nicely done!
