### ISSUE TITLE
disabled state of interactive-primary is not viewable

### ISSUE THREAD

**Issue by ay13** [JavierM42/tailwind-material-colors#5]
I edited the main example page at https://tailwind-material-colors-docs.vercel.app/ to generate the screenshots.

bg-primary
![b0416c646562fa5999533d25bc8e2116](https://github.com/JavierM42/tailwind-material-colors/assets/72563/81be7d3e-5fc2-497a-b142-1bcf5d355abb)

disabled
![78755c745cae03f04f5d073d68e74812](https://github.com/JavierM42/tailwind-material-colors/assets/72563/e09f0b3e-3c1d-4544-abdb-6971d0b9f1d6)

**Comment by JavierM42** [comment]
That's because the Material guidelines define the disabled state of the button as its on-color with 12% opacity for the background and 38% opacity for the text.

If you scroll to filled button or filled tonal button and click on the disabled specs [on this page](https://m3.material.io/components/buttons/specs):

<img width="993" alt="Screenshot 2023-11-08 at 10 48 39" src="https://github.com/JavierM42/tailwind-material-colors/assets/32175149/95777aea-6fb0-4f70-9fbf-f522d5c5aa3d">

Since the on color for primary is white, it's barely noticeable over a light background, but I don't think I should fix it, that's on Google 😅. Here's how it looks over a dark background:

<img width="400" alt="Screenshot 2023-11-08 at 10 46 09" src="https://github.com/JavierM42/tailwind-material-colors/assets/32175149/35605e12-9267-43e9-abf2-1cf272985baa">

**Comment by ay13** [comment]
The Filled (https://m3.material.io/components/buttons/specs#cbfd91a6-d688-4be7-9a69-672549de3ea9) and Tonal (https://m3.material.io/components/buttons/specs#6ce8b926-87c4-4600-9bec-5deb4aaa65d8) list `on-surface` as the disabled color.

![Screenshot 2023-11-08 at 9 38 49 AM](https://github.com/JavierM42/tailwind-material-colors/assets/72563/90d57ea2-0213-4122-8bb5-fa479ed9ae6a)

**Comment by JavierM42** [comment]
Oops, you're definitely right. Thanks for the heads up.

I'll try to fix it it, but it could take some time, I maintain this project on my free time and that's on short supply at the moment.

**Comment by beautyfree** [comment]
faced the same problem and hope to see fix soon

**Comment by JavierM42** [comment]
I gave it a look and the fix was simple enough. Should be solved if you update to the lastest version (1.1.3).

Thanks for the feedback! Don't hesitate to open another issue if this doesn't fully work or you find anything else ✨
